# Generated by Django 4.1.7 on 2023-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default='2023-03-14'),
        ),
        migrations.AlterModelTable(
            name='phone',
            table='Phone',
        ),
    ]
